### ISSUE TITLE
sostituzione "Bitcoin People Wallet" con "Baloo - Bitcoin Wallet"

### ISSUE THREAD

**Issue by BTCPsrld** [btcp-srl/baloo_green_android#1]
Sostituire tutti i punti del codice dove c'è scritto Bitcoin People Wallet:

In particolare
1 Titolo in fase di inserimento pin 
2 nella parte impostazioni per il log out 
3 Nome della versione
4 opzione a destra con link

**Comment by tetofonta** [comment]
Risolto, 2108617a1b349fa3f7a9e25fb8b091895565bf2d
